### ISSUE TITLE
Make repo more community-friendly

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/snark-artifacts#18]
**Tasks**:

- [x] Make this repository compliant with [community standards](https://github.com/privacy-scaling-explorations/snark-artifacts/community)
- [x] Update overview
- [x] Add good first issues
- [x] Add more instructions on how to add new artifacts and contribute
- [x] Write a README file for each package
